### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by hvt** [chubbyphp/chubbyphp-container#2]
Hey @dominikzogg, this looks great!

Saw some of your comments on Twitter (https://twitter.com/dominikzogg/status/1294519387052023814?s=19), and was wondering about them :):

* How much faster is it then Pimple?
* The term for a prototype factory was unknown to me, and I find it a bit confusing. Where does it originate from? 
* How would you stand on including an alias feature? (used to add interfaces as aliases to actual implementations) 

(It's hard to express tone, but please, read this all as positive questions :).)

**Comment by dominikzogg** [comment]
Hello @hvt 

- Please check https://rawgit.com/kocsismate/php-di-container-benchmarks/master/var/benchmark.html

- Its the same as https://github.com/silexphp/pimple#defining-factory-services within pimple, but in my opinion a service definition closure is already a factory by itself. So the term was already used. Cause the Symfony container used the term prototype i've added the term prototypeFactory. I only added this functionality, cause there might be user like it or used it with pimple. In my opinion a factory service would be a better idea.

- By definition a new factory returning the original service, for example: https://github.com/chubbyphp/chubbyphp-laminas-config/blob/master/src/Config.php#L118-L120

**Comment by hvt** [comment]
> * Please check https://rawgit.com/kocsismate/php-di-container-benchmarks/master/var/benchmark.html

Nice!

> * Its the same as https://github.com/silexphp/pimple#defining-factory-services within pimple, but in my opinion a service definition closure is already a factory by itself. So the term was already used.

Pimple has indeed no explicit naming for shared services, all defined closures are shared. Their `->factory()` naming is somewhat in conflict with what you mean with a factory (a shared one) :].

Although I was more referring to the prototype term I was unaware of :].

> Cause the Symfony container used the term prototype i've added the term prototypeFactory. I only added this functionality, cause there might be user like it or used it with pimple.

That is as far as I know quite an [old term](https://symfony.com/blog/new-in-symfony-2-8-deprecating-scopes-and-introducing-shared-services). I like their current `shared` & `not shared` naming better.

> In my opinion a factory service would be a better idea.

But I can imagine there are use-cases where you do _not_ want to return the same instance after creation (i.e. a non-shared service), right? Or am I misunderstanding what you meant :]?

> * By definition a new factory returning the original service, for example: https://github.com/chubbyphp/chubbyphp-laminas-config/blob/master/src/Config.php#L118-L120

Ah yes, that is a nice, simple, and elegant solution, thanks.

**Comment by dominikzogg** [comment]
> But I can imagine there are use-cases where you do _not_ want to return the same instance after creation (i.e. a non-shared service), right? Or am I misunderstanding what you meant :]?

I am with you, but in such cases i would prefer having a separate class registered as a service with a method `create`. (factory class).

**Comment by hvt** [comment]
Ah I see, you would recommend to let such cases (unshared services) be handled by the application, not the DI container.

Would seem appropriate to me to remove the prototype methods and suggest this approach in the docs instead. But of course, not handy in regard to BC :].

Thanks for your responses, will probably be using this, so thank you very much :]!

**Comment by dominikzogg** [comment]
@hvt thx for asking

PS: I've added them in version 1.1 cause i meant i need those unshared services to implement laminas config, but it wasn't the case https://github.com/chubbyphp/chubbyphp-laminas-config. Version 1.0 was event faster without the additional check.
